name    'jhoblitt-port389'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-port389'
source 'https://github.com/jhoblitt/puppet-port389.git'
summary 'Manage port 389 Directory Server'
description 'Manage port 389 Directory Server'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
