require 'spec_helper'

#describe 'port389::instance::ssl', :type => :define do
describe 'port389::instance', :type => :define do
  let(:facts) {{ :osfamily => 'RedHat' }}
  let(:pre_condition) { 'include port389' }
  let(:title) { 'ldap1' }

  context 'enable_ssl =>' do
    context 'true' do
      let(:params) do
        {
  #        :root_dn     => 'admin',
  #        :root_dn_pwd => 'admin',
  #        :server_port => 389,
          :enable_ssl   => true,
          :ssl_cert     => '/dne/cert.pem',
          :ssl_key      => '/dne/key.pem',
          :ssl_ca_certs => {
            'AlphaSSL CA'        => '/tmp/alphassl_intermediate.pem',
            'GlobalSign Root CA' => '/tmp/globalsign_root.pem',
          }
        }
      end

      it do
        should contain_file('ssl_enable.ldif').with({
          :ensure => 'file',
          :path   => '/var/lib/dirsrv/setup/ssl_enable.ldif',
          :owner  => 'root',
          :group  => 'root',
          :mode   => '0640',
          :source => 'puppet:///modules/port389/ssl_enable.ldif',
          :backup => false,
        })
      end

      it do
        should contain_file('addRSA.ldif').with({
          :ensure => 'file',
          :path   => '/var/lib/dirsrv/setup/addRSA.ldif',
          :owner  => 'root',
          :group  => 'root',
          :mode   => '0640',
          :source => 'puppet:///modules/port389/addRSA.ldif',
          :backup => false,
        })
      end

      it do
        should contain_file('set_secureport_ldap1.ldif').with({
          :ensure  => 'file',
          :path    => '/var/lib/dirsrv/setup/set_secureport_ldap1.ldif',
          :owner   => 'root',
          :group   => 'root',
          :mode    => '0640',
          :backup  => false,
          :content => <<-EOS
dn: cn=config
changetype: modify
add: nsslapd-secureport
nsslapd-secureport: 636
          EOS
        })
      end

      it do
        should contain_exec('ssl_enable.ldif-ldap1').with({
          :path      => [ '/bin', '/usr/bin' ],
          :logoutput => true,
        })
      end

      it do
        should contain_exec('addRSA.ldif-ldap1').with({
          :path      => [ '/bin', '/usr/bin' ],
          :logoutput => true,
        })
      end

      it do
        should contain_exec('set_secureport_ldap1.ldif').with({
          :path      => [ '/bin', '/usr/bin' ],
          :logoutput => true,
        })
      end

      it do
        should contain_file('pin.txt-ldap1').with({
          :ensure  => 'file',
          :path    => '/etc/dirsrv/slapd-ldap1/pin.txt',
          :owner   => 'nobody',
          :group   => 'nobody',
          :mode    => '0400',
          :content => 'Internal (Software) Token:admin',
        })
      end

      it do
        should contain_nssdb__create('/etc/dirsrv/slapd-ldap1').with({
          :owner_id       => 'nobody',
          :group_id       => 'nobody',
          :mode           => '0660',
          :password       => 'admin',
          :manage_certdir => false,
        })
      end

      it do
        should contain_nssdb__add_cert_and_key('/etc/dirsrv/slapd-ldap1').with({
          :nickname => 'Server-Cert',
          :cert     => '/dne/cert.pem',
          :key      => '/dne/key.pem',
        })
      end

      # note that the nssdb::add_cert resources are dynamically generated by the
      # port389_nssdb_add_cert() function
      it do
        should contain_nssdb__add_cert('/etc/dirsrv/slapd-ldap1-AlphaSSL CA').with({
          :certdir  => '/etc/dirsrv/slapd-ldap1',
          :nickname => 'AlphaSSL CA',
          :cert     => '/tmp/alphassl_intermediate.pem',
        })
      end

      it do
        should contain_nssdb__add_cert('/etc/dirsrv/slapd-ldap1-GlobalSign Root CA').with({
          :certdir  => '/etc/dirsrv/slapd-ldap1',
          :nickname => 'GlobalSign Root CA',
          :cert     => '/tmp/globalsign_root.pem',
        })
      end
    end # true

    context 'false' do
      let(:params) {{ :enable_ssl  => false }}

      it { should_not contain_file('ssl_enable.ldif') }
      it { should_not contain_file('addRSA.ldif') }
      it { should_not contain_exec('ssl_enable.ldif-ldap1') }
      it { should_not contain_exec('addRSA.ldif-ldap1') }
      it { should_not contain_file('pin.txt-ldap1') }
      it { should_not contain_nssdb__create('/etc/dirsrv/slapd-ldap1') }
      it { should_not contain_nssdb__add_cert_and_key('/etc/dirsrv/slapd-ldap1') }
    end # false

    context 'foo' do
      let(:params) {{ :enable_ssl  => 'foo' }}

      it 'should fail' do
        expect { should compile }.to raise_error(/is not a boolean/)
      end
    end # foo
  end # enable_ssl =>

  context 'ssl_cert =>' do
    let(:params) do
      {
        :enable_ssl => true,
        :ssl_key    => '/dne/key.pem',
      }
    end

    context '/dne/cert.pem' do
      before { params[:ssl_cert] = '/dne/cert.pem' }

      it do
        should contain_nssdb__add_cert_and_key('/etc/dirsrv/slapd-ldap1').with({
          :nickname => 'Server-Cert',
          :cert     => '/dne/cert.pem',
          :key      => '/dne/key.pem',
        })
      end
    end

    context '../dne/cert.pem' do
      before { params[:ssl_cert] = '../dne/cert.pem' }

      it 'should fail' do
        expect { should compile }.to raise_error(/is not an absolute path./)
      end
    end
  end # ssl_cert =>

  context 'ssl_key =>' do
    let(:params) do
      {
        :enable_ssl => true,
        :ssl_cert   => '/dne/cert.pem',
      }
    end

    context '/dne/key.pem' do
      before { params[:ssl_key] = '/dne/key.pem' }

      it do
        should contain_nssdb__add_cert_and_key('/etc/dirsrv/slapd-ldap1').with({
          :nickname => 'Server-Cert',
          :cert     => '/dne/cert.pem',
          :key      => '/dne/key.pem',
        })
      end
    end

    context '../dne/key.pem' do
      before { params[:ssl_key] = '../dne/key.pem' }

      it 'should fail' do
        expect { should compile }.to raise_error(/is not an absolute path./)
      end
    end
  end # ssl_key =>

  context 'ca_certs =>' do
    let(:params) do
      {
        :enable_ssl => true,
        :ssl_cert   => '/dne/cert.pem',
        :ssl_key    => '/dne/key.pem',
      }
    end

    context '{}' do
      before { params[:ssl_ca_certs] = {} }

      it { should have_nssdb__add_cert_resource_count(0) }
    end

    context '{ ... }' do
      before do
        params[:ssl_ca_certs] = {
          'AlphaSSL CA'        => '/tmp/alphassl_intermediate.pem',
          'GlobalSign Root CA' => '/tmp/globalsign_root.pem',
        }
      end

      it { should have_nssdb__add_cert_resource_count(2) }

      it do
        should contain_nssdb__add_cert('/etc/dirsrv/slapd-ldap1-AlphaSSL CA').with({
          :nickname => 'AlphaSSL CA',
          :certdir  => '/etc/dirsrv/slapd-ldap1',
          :cert     => '/tmp/alphassl_intermediate.pem',
        })
      end

      it do
        should contain_nssdb__add_cert('/etc/dirsrv/slapd-ldap1-GlobalSign Root CA').with({
          :nickname => 'GlobalSign Root CA',
          :certdir  => '/etc/dirsrv/slapd-ldap1',
          :cert     => '/tmp/globalsign_root.pem',
        })
      end
    end

    context 'foo' do
      before { params[:ssl_ca_certs] = 'foo' }

      it 'should fail' do
        expect { should compile }.to raise_error(/is not a Hash./)
      end
    end

  end # ca_certs =>

end
